### ISSUE TITLE
No such file: librispeech_models/exp/chain_cleaned/tdnn_1_sp/final.txt

### ISSUE THREAD

**Issue by pkadambi** [MarceloSancinetti/epa-gop-pykaldi#2]
This is an error that I get when I run the data preparation 
`python run_dataprep.py --config configs/dataprep.yaml`

The error:
`FileNotFoundError: [Errno 2] No such file or directory: 'librispeech_models/exp/chain_cleaned/tdnn_1d_sp/final.txt'`
 
It seems like the final.txt file specified in dataprep.yaml wasn't included in the downloaded model files?

**Comment by MarceloSancinetti** [comment]
Hello @pkadambi, try running this command from the epa-gop-pykaldi directory: 
`nnet3-copy --binary=false librispeech_models/exp/chain_cleaned/tdnn_1d_sp/final.mdl librispeech_models/exp/chain_cleaned/tdnn_1d_sp/final.txt` 
That should generate the final.txt file from the downloaded final.mdl. It should happen automatically as part of the dataprep process but for some reason in this case it didn't happen. 
If the command isn't found, it's because you don't have the path to the Kaldi binaries in your PATH
